### ISSUE TITLE
android.view.InflateException: Binary XML file line #8: Binary XML file line #8: Error inflating class com.tayfuncesur.stepper.Stepper

### ISSUE THREAD

**Issue by sherwin14** [TayfunCesur/Stepper#4]
Hi I'm trying to implement this library in my application but unfortunately I encountered this error.

Here is the Log.

`E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.escoglobal.escolifeapps, PID: 20077
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.escoglobal.escolifeapps/com.escoglobal.escolifeapps.ui.signup.RegistrationActivity}: android.view.InflateException: Binary XML file line #8: Binary XML file line #8: Error inflating class com.tayfuncesur.stepper.Stepper
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2913)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: android.view.InflateException: Binary XML file line #8: Binary XML file line #8: Error inflating class com.tayfuncesur.stepper.Stepper
     Caused by: android.view.InflateException: Binary XML file line #8: Error inflating class com.tayfuncesur.stepper.Stepper
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:647)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:469)
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
        at com.escoglobal.escolifeapps.ui.signup.RegistrationActivity.onCreate(RegistrationActivity.java:29)
        at android.app.Activity.performCreate(Activity.java:7136)
        at android.app.Activity.performCreate(Activity.java:7127)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lkotlin/jvm/internal/Intrinsics;
        at com.tayfuncesur.stepper.Stepper.<init>(Unknown Source:2)
        at com.tayfuncesur.stepper.Stepper.<init>(Stepper.kt:12)
        at com.tayfuncesur.stepper.Stepper.<init>(Unknown Source:6)
        at java.lang.reflect.Constructor.newInstance0(Native Method) 
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343) 
        at android.view.LayoutInflater.createView(LayoutInflater.java:647) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:863) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:469) 
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
        at com.escoglobal.escolifeapps.ui.signup.RegistrationActivity.onCreate(RegistrationActivity.java:29) 
        at android.app.Activity.performCreate(Activity.java:7136) 
        at android.app.Activity.performCreate(Activity.java:7127) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
E/AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "kotlin.jvm.internal.Intrinsics" on path: DexPathList[[zip file "/data/app/com.escoglobal.escolifeapps-bQjVNDoeQJxwjuOhbJ7VDg==/base.apk", zip file "/data/app/com.escoglobal.escolifeapps-bQjVNDoeQJxwjuOhbJ7VDg==/split_lib_dependencies_apk.apk", zip file "/data/app/com.escoglobal.escolifeapps-bQjVNDoeQJxwjuOhbJ7VDg==/split_lib_resources_apk.apk", zip file "/data/app/com.escoglobal.escolifeapps-bQjVNDoeQJxwjuOhbJ7VDg==/split_lib_slice_0_apk.apk", zip file "/data/app/com.escoglobal.escolifeapps-bQjVNDoeQJxwjuOhbJ7VDg==/split_lib_slice_1_apk.apk", zip file "/data/app/com.escoglobal.escolifeapps-bQjVNDoeQJxwjuOhbJ7VDg==/split_lib_slice_2_apk.apk", zip file "/data/app/com.escoglobal.escolifeapps-bQjVNDoeQJxwjuOhbJ7VDg==/split_lib_slice_3_apk.apk", zip file "/data/app/com.escoglobal.escolifeapps-bQjVNDoeQJxwjuOhbJ7VDg==/split_lib_slice_4_apk.apk", zip file "/data/app/com.escoglobal.escolifeapps-bQjVNDoeQJxwjuOhbJ7VDg==/split_lib_slice_5_apk.apk", zip file "/data/app/com.escoglobal.escolifeapps-bQjVNDoeQJxwjuOhbJ7VDg==/split_lib_slice_6_apk.apk", zip file "/data/app/com.escoglobal.escolifeapps-bQjVNDoeQJxwjuOhbJ7VDg==/split_lib_slice_7_apk.apk", zip file "/data/app/com.escoglobal.escolifeapps-bQjVNDoeQJxwjuOhbJ7VDg==/split_lib_slice_8_apk.apk", zip file "/data/app/com.escoglobal.escolifeapps-bQjVNDoeQJxwjuOhbJ7VDg==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.escoglobal.escolifeapps-bQjVNDoeQJxwjuOhbJ7VDg==/lib/x86, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        	... 31 more
    	Suppressed: java.io.IOException: No original dex files found for dex location /data/app/com.escoglobal.escolifeapps-bQjVNDoeQJxwjuOhbJ7VDg==/split_lib_resources_apk.apk
        at dalvik.system.DexFile.openDexFileNative(Native Method)
        at dalvik.system.DexFile.openDexFile(DexFile.java:354)
        at dalvik.system.DexFile.<init>(DexFile.java:101)
        at dalvik.system.DexFile.<init>(DexFile.java:75)
        at dalvik.system.DexPathList.loadDexFile(DexPathList.java:394)
        at dalvik.system.DexPathList.makeDexElements(DexPathList.java:354)
        at dalvik.system.DexPathList.<init>(DexPathList.java:164)
        at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:74)
        at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:65)
        at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:64)
        at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:73)
        at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:88)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:74)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:40)
        at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:727)
        at android.app.LoadedApk.getClassLoader(LoadedApk.java:810)
        at android.app.LoadedApk.getResources(LoadedApk.java:1032)
        at android.app.ContextImpl.createAppContext(ContextImpl.java:2345)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5749)
        at android.app.ActivityThread.access$1100(ActivityThread.java:199)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
        		... 6 more`

**Comment by sherwin14** [comment]
Fixed by adding this: implementation 'org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.3.21'
